apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
rules:
- verbs:
    - '*'
  apiGroups:
    - ''
  resources:
    - pods
- verbs:
    - '*'
  apiGroups:
    - ''
  resources:
    - services
