kind: Job
apiVersion: batch/v1
metadata:
  name: spark-operator-webhook-init
  labels:
    app.kubernetes.io/instance: spark-operator
    app.kubernetes.io/name: spark-operator
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 6
  template:
    metadata:
      name: spark-operator-webhook-init
      labels:
        job-name: spark-operator-webhook-init
    spec:
      containers:
        - name: main
          env:
            - name: NAMESPACE
              valueFrom: 
                fieldRef:
                  fieldPath: metadata.namespace
          image: 'gcr.io/spark-operator/spark-operator:v1beta2-1.2.0-3.0.0'
          command:
            - /usr/bin/gencerts.sh
            - '-n'
            - $(NAMESPACE)
            - '-s'
            - spark-operator-webhook
            - '-p'
          imagePullPolicy: IfNotPresent
          securityContext: {}
      restartPolicy: OnFailure
      serviceAccountName: spark-operator
