apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  name: s2i-minimal-lmod-notebook
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/guimou/s2i-minimal-lmod-notebook
    from:
      kind: DockerImage
      name: quay.io/guimou/s2i-minimal-lmod-notebook:0.1.23
    name: "3.6"
    referencePolicy:
      type: Source
